services:
  ui:
    build: .
    environment:
      - PORT=3000
      - HOSTNAME=ui
    networks:
      - ui-miseenscreen
    restart: 'always'
networks:
  ui-miseenscreen:
    driver: bridge
    name: miseenscreen